espanol_ingles={'casa':'House',
'perro':'dog',
'dinosaurio':'dinosaur',
'humano':'human',
'persona':'person',
'gente':'people',
'hombre':'men',
'mujer':'woman',
'bebé':'baby',
'adolescente':'Teen',
'adulto':'adult',
'anciano':'old man',
'individuo':'individual',
'comida':'food',
'bebida':'beverage',
'vegetal':'vegetable',
'planta':'plant',
'flor':'flower',
'fruta':'fruit'}

ingles_frances={'House':'Loger',
'dog':'chien',
'dinosaur':'dinosaure',
'human':'Humain',
'person':'la personne',
'people':'personnes',
'men':'Hommes',
'woman':'femme',
'baby':'bébé',
'Teen':'Ado',
'adult':'adulte',
'old man':'vieil homme',
'individual':'individuel',
'food':'aliments',
'beverage':'boisson',
'vegetable':'légume',
'plant':'plante',
'flower':'fleur',
'fruit':'fruit'}

frances_aleman={'Loger':'Unterkunft',
'chien':'Hund ',
'dinosaure':'Dinosaurier',
'Humain':'Menschlich',
'la personne':'die Person',
'personnes':'Personen',
'Hommes':'Männer',
'femme':'Frauen',
'bébé':'Baby',
'Ado':'jugendlich',
'adulte':'Erwachsene',
'vieil homme':'alter Mann',
'individuel':'Individuell',
'aliments':'Lebensmittel',
'boisson':'Getränk',
'légume':'Gemüse',
'plante':'Pflanze',
'fleur':'Blume',
'fruit':'Obst'}



